### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application at (vi2IPA(lines))

### ISSUE THREAD

**Issue by unabrijed** [v-nhandt21/Viphoneme#3]
We are working on a research paper and we need text conversion to phonemes and we are utilising your great work. Thanks for that but....
`Traceback (most recent call last):
      File "d:\IR Research\complete_phonetics.py", line 269, in <module>
        phoneme_trans.append(vi2IPA(lines))
      File "C:\Users\brije\AppData\Local\Programs\Python\Python310\lib\site-packages\viphoneme\__init__.py", line 578, in vi2IPA
        TN= TTSnorm(text)
      File "C:\Users\brije\AppData\Local\Programs\Python\Python310\lib\site-packages\vinorm\__init__.py", line 25, in TTSnorm
        subprocess.check_call(Command, env=myenv, cwd=A)
      File "C:\Users\brije\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 364, in check_call
        retcode = call(*popenargs, **kwargs)
      File "C:\Users\brije\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 345, in call
        with Popen(*popenargs, **kwargs) as p:
      File "C:\Users\brije\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Users\brije\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    OSError: [WinError 193] %1 is not a valid Win32 application
`
This error is shown in the terminal. Please lead me to a solution.

**Comment by v-nhandt21** [comment]
The error is in line 578, C:\Users\brije\AppData\Local\Programs\Python\Python310\lib\site-packages\viphoneme\__init__.py

You could solve it quickly by commenting that line:  vi2IPA TN= TTSnorm(text)

This line is used for text normalization for the Vietnamese language (convert 5h30 to spoken text for example), this text normalization version only supports Linux.

p/s: Are you working on TTS for Vietnamese? This phonology model is g2p version for Vietnamese

**Comment by unabrijed** [comment]
> p/s: Are you working on TTS for Vietnamese? This phonology model is g2p version for Vietnamese
Not TTS, g2p.
